begin;

create extension if not exists pgtap with schema extensions;
select extensions.no_plan();

select extensions.is((select count(*)::integer from information_schema.columns where table_schema = 'public' and table_name = 'client_profiles'), 4, 'profile has exactly four columns');
select extensions.ok((select relrowsecurity from pg_class where oid = 'public.client_profiles'::regclass), 'profile RLS enabled');
select extensions.is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'client_profiles'), 1, 'exactly one policy, no permissive OR alternatives');
select extensions.ok(exists(select 1 from pg_policies where schemaname = 'public' and tablename = 'client_profiles' and policyname = 'client_profiles_owner_active_live_session' and cmd = 'SELECT' and roles = array['authenticated']::name[]), 'policy is authenticated SELECT only');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'SELECT'), 'anon has no SELECT');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'INSERT'), 'anon has no INSERT');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'UPDATE'), 'anon has no UPDATE');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'DELETE'), 'anon has no DELETE');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'TRUNCATE'), 'anon has no TRUNCATE');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'REFERENCES'), 'anon has no REFERENCES');
select extensions.ok(not has_table_privilege('anon', 'public.client_profiles', 'TRIGGER'), 'anon has no TRIGGER');
select extensions.ok(has_table_privilege('authenticated', 'public.client_profiles', 'SELECT'), 'authenticated has SELECT');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'INSERT'), 'authenticated has no INSERT');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'UPDATE'), 'authenticated has no UPDATE');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'DELETE'), 'authenticated has no DELETE');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'TRUNCATE'), 'authenticated has no TRUNCATE');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'REFERENCES'), 'authenticated has no REFERENCES');
select extensions.ok(not has_table_privilege('authenticated', 'public.client_profiles', 'TRIGGER'), 'authenticated has no TRIGGER');
select extensions.ok(not exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = 'client_profiles' and (has_column_privilege('authenticated', 'public.client_profiles', column_name, 'INSERT') or has_column_privilege('authenticated', 'public.client_profiles', column_name, 'UPDATE') or has_column_privilege('anon', 'public.client_profiles', column_name, 'SELECT'))), 'no column-grant loopholes');
select extensions.ok((select bool_and(has_table_privilege('service_role', 'public.client_profiles', privilege)) from unnest(array['SELECT','INSERT','UPDATE','DELETE']) as privilege), 'local provisioning role has all CRUD privileges');
select extensions.ok(not has_table_privilege('service_role', 'public.client_profiles', 'TRUNCATE'), 'provisioning role has no TRUNCATE');
select extensions.ok(not has_table_privilege('service_role', 'public.client_profiles', 'REFERENCES'), 'provisioning role has no REFERENCES');
select extensions.ok(not has_table_privilege('service_role', 'public.client_profiles', 'TRIGGER'), 'provisioning role has no TRIGGER');
select extensions.ok(not has_table_privilege('authenticated', 'auth.sessions', 'SELECT'), 'authenticated cannot read auth.sessions');
select extensions.ok(not has_table_privilege('anon', 'auth.sessions', 'SELECT'), 'anon cannot read auth.sessions');
select extensions.ok(has_schema_privilege('authenticated', 'private', 'USAGE'), 'authenticated can resolve helper for RLS');
select extensions.ok(not has_schema_privilege('authenticated', 'private', 'CREATE'), 'authenticated cannot replace helper');
select extensions.ok(not has_schema_privilege('anon', 'private', 'USAGE'), 'anon cannot resolve private helper');
select extensions.ok(has_function_privilege('authenticated', 'private.client_session_is_live()', 'EXECUTE'), 'authenticated has helper EXECUTE');
select extensions.ok(not has_function_privilege('anon', 'private.client_session_is_live()', 'EXECUTE'), 'anon has no helper EXECUTE');
select extensions.ok(not has_function_privilege('service_role', 'private.client_session_is_live()', 'EXECUTE'), 'provisioning role does not need helper EXECUTE');
select extensions.ok(not exists(select 1 from pg_proc, lateral aclexplode(proacl) as privilege where oid = 'private.client_session_is_live()'::regprocedure and privilege.grantee = 0), 'PUBLIC has no helper EXECUTE');
select extensions.ok((select prosecdef from pg_proc where oid = 'private.client_session_is_live()'::regprocedure), 'helper is SECURITY DEFINER');
select extensions.is((select proowner::regrole::text from pg_proc where oid = 'private.client_session_is_live()'::regprocedure), 'postgres', 'helper has explicit trusted owner');
select extensions.ok((select proconfig @> array['search_path=""'] from pg_proc where oid = 'private.client_session_is_live()'::regprocedure), 'helper has empty search_path');
select extensions.is((select pronargs::integer from pg_proc where oid = 'private.client_session_is_live()'::regprocedure), 0, 'helper accepts no identity parameters');
select extensions.is((select prorettype::regtype::text from pg_proc where oid = 'private.client_session_is_live()'::regprocedure), 'boolean', 'helper returns boolean only');
select extensions.ok(not has_schema_privilege('authenticated', 'public', 'CREATE'), 'clients cannot shadow public objects');

select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', ''), '23514', null, 'empty name rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', ' Leading'), '23514', null, 'leading whitespace rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', 'Trailing '), '23514', null, 'trailing whitespace rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', U&'\00A0Synthetic'), '23514', null, 'leading Unicode whitespace rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', 'Synthetic' || chr(1)), '23514', null, 'control character rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', 'Synthetic' || chr(127)), '23514', null, 'DEL control character rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', repeat('a',101)), '23514', null, '101 characters rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, null)', :'fixture_no_profile'), '23502', null, 'null name rejected');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name,status) values (%L, %L, %L)', :'fixture_no_profile', 'Synthetic', 'approved'), '23514', null, 'unapproved status rejected');
select extensions.throws_ok('insert into public.client_profiles(user_id,name) values (''00000000-0000-0000-0000-000000000000'', ''Synthetic'')', '23503', null, 'profile must belong to Auth identity');
select extensions.lives_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', repeat(U&'\00E9',100)), '100 Unicode characters accepted');
select extensions.throws_ok(format('insert into public.client_profiles(user_id,name) values (%L, %L)', :'fixture_no_profile', 'Synthetic Duplicate'), '23505', null, 'one profile per Auth identity');
select extensions.is((select status from public.client_profiles where user_id = :'fixture_no_profile'::uuid), 'pending', 'new profile defaults to pending');
select extensions.ok((select created_at is not null from public.client_profiles where user_id = :'fixture_no_profile'::uuid), 'creation timestamp defaults correctly');

select * from extensions.finish();
rollback;
