project_id = "taxtrax-client-auth"

[api]
enabled = true
port = 55321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17

[db.pooler]
enabled = false
port = 55329

[db.seed]
enabled = false
sql_paths = []

[realtime]
enabled = false

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 55324

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/portal", "http://127.0.0.1:3000/portal", "http://localhost:3000/api/auth/recovery/callback", "http://127.0.0.1:3000/api/auth/recovery/callback", "http://localhost:3000/api/auth/activation/callback", "http://127.0.0.1:3000/api/auth/activation/callback"]
enable_signup = false
enable_anonymous_sign_ins = false
enable_refresh_token_rotation = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false

[edge_runtime]
enabled = false

[analytics]
enabled = false

[functions.send-recovery-email]
verify_jwt = false

[functions.submit-access-request]
verify_jwt = false

[functions.review-access-requests]
verify_jwt = false
